name: Deploy Bitcoin Core to EKS

on:
    workflow_dispatch:
        inputs:
            environment:
              description: 'Environment to deploy to: aws'
              required: true
              type: choice
              options:
                - "bitcoin-core"
#   push:
#     branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name bitcoin --region us-east-2

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/bitcoin-deployment.yaml --validate=false
          kubectl apply -f k8s/bitcoin-network-policy.yml
          kubectl apply -f k8s/bitcoin-pvc.yml
          kubectl apply -f k8s/bitcoin-service.yml

