name: Deploy Bitcoin Core to EKS

on:
    workflow_dispatch:
        inputs:
            environment:
              description: 'Environment to deploy to: aws'
              required: true
              type: choice
              options:
                - "bitcoin-core"
#   push:
#     branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

    #   - name: Get AWS EKS cluster endpoint
    #     uses: aws-actions/eks-describe-cluster@v1
    #     with:
    #         name: bitcoin
    #         output: endpoint
    #   - name: Get Kubernetes API credentials
    #     uses: aws-actions/eks-get-token@v1
    #     with:
    #         cluster-name: bitcoin

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name bitcoin

      - name: Apply Kubernetes manifests
        run: |
            kubectl config set-cluster default --server=$ENDPOINT --insecure-skip-tls-verify=true --token=$TOKEN
            kubectl apply -f k8s/ 
            kubectl apply -f elastic-agent-managed-kubernetes.yml

      - name: Verify Pod Health
        run: |
          while [[ $(kubectl get pods -l app=bitcoin -o jsonpath='{.items[*].status.phase}') != "Running" ]]; do echo "waiting for pod to be in Running state" && sleep 10; done
          kubectl logs -l app=bitcoin
