name: Deploy Bitcoin Core to EKS

on:
    workflow_dispatch:
        
#   push:
#     branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: region-name

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name cluster-name

      - name: Apply Kubernetes manifests
        run: kubectl apply -f kubernetes/deployment.yaml -f kubernetes/service.yaml

      - name: Verify Pod Health
        run: |
          while [[ $(kubectl get pods -l app=bitcoin -o jsonpath='{.items[*].status.phase}') != "Running" ]]; do echo "waiting for pod to be in Running state" && sleep 10; done
          kubectl logs -l app=bitcoin
