name: Deploy Bitcoin Core to EKS

on:
    workflow_dispatch:
        inputs:
            environment:
              description: 'Environment to deploy to: aws'
              required: true
              type: choice
              options:
                - "bitcoin-core"
#   push:
#     branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name bitcoin --region us-east-2

      # - name: Get current Kubernetes context
      #   run: kubectl config current-context
      

      # - name: Cat kubernetes
      #   run: cat $HOME/.kube/config

      - name: Apply Kubernetes Deployment Manifest
        run: kubectl apply -f k8s/bitcoin-deployment.yaml 

      # - name: Apply Kubernetes Network Policy
      #   run: kubectl apply -f k8s/bitcoin-network-policy.yml

      # - name: Apply Kubernetes PVC Manifest
      #   run: kubectl apply -f k8s/bitcoin-pvc.yml

      # - name: Apply Kubernetes Service Manifest
      #   run: kubectl apply -f k8s/bitcoin-service.yml

      # - name: Verify Deployment
      #   run: kubectl rollout status deployment/bitcoin-core-deployment -n bitcoin

      # - name: Get Service Details
      #   run: kubectl get services -n bitcoin

      # - name: Get PVC Details
      #   run: kubectl get pvc -n bitcoin
