name: 'Terraform IAM'

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to: t, d , s, p'
                required: true
                type: choice
                options:
                - "test"
                - "production"
                - "development"
                - "staging"
            action:
                description: 'Action to perform: apply or destroy'
                required: true
                type: choice
                options:
                  - "apply"
                  - "destroy"

    # push:
    #  branches: [ "main" ]
    # pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: List directory structure
      run: ls -R
      
     # Change working directory for Terraform commands
    - name: Change to Terraform Directory
      run: cd tf-aws-resources


    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: tf-aws-resources

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: tf-aws-resources

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: tf-aws-resources

    - name: Terraform Apply or Destroy
      run: |
        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
          terraform apply -auto-approve
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        fi
      working-directory: tf-aws-resources
      if: github.event.inputs.environment == 'production'
