name: 'Terraform Destroy'

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to: t, d , s, p'
                required: true
                type: choice
                options:
                - "test"
                - "production"
                - "development"
                - "staging"

    # push:
    #  branches: [ "main" ]
    # pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION }}
    
     # Change working directory for Terraform commands
    - name: Change to Terraform Directory
      run: cd tf-aws-resources

    - name: Terraform Destroy
      if: github.event.inputs.environment == 'production'
      run: terraform destroy -auto-approve -input=false
      working-directory: tf-aws-resources